### PR TITLE
pygls update

### PR DESCRIPTION
**Pull request by dimbleby**
Not for merging, certainly until pygls next releases.

I've been wondering since https://github.com/pappasam/jedi-language-server/pull/78#issuecomment-787217980 whether https://github.com/openlawlibrary/pygls/pull/139 was going to be a good thing, and at the weekend I kind of got sucked into going down the path of finding out.

This - and prompting that project to merge their longstanding PR - is the result.

Obviously not for merging until there's an actual pygls release and pyproject.toml can be updated to point at that, rather than to a local checkout.  But I figured I should get this in front of you sooner rather than later in case you hate it, or want changes, or were about to duplicate the work, or whatever.

I made a series of commits:

- first just updating to new pygls, mostly mechanical, allowed removal of a couple of hokey workarounds
- then noticed that pygls gave convenient access to ClientCapabilities, so removed them from the initialise-params-parser
- then decided that with pydantic now in the dependency tree anyway, initialization options could be very conveniently handled by using that, I think it's turned out nicely.  So nicely that there was really nothing left to unit test, not sure whether that'll be controversial!

What else interesting?  Oh, bumped min python version to 3.6.1, some of our dependencies need that to be able to update to recent versions and I think it should be uncontroversial: surely very few even of those who are stuck on python 3.6 are stuck on python 3.6.0.

### CODE REVIEW

**Comment by pappasam** [comment]
Wow, this looks great! At a glance, I have no major issues with the direction you've taken this. I'll wait for pygls to release the next version and then immediately start testing out this PR / giving you any functionality-based feedback that I find. Thanks for pushing this ahead, I'm very pleased with all the simplifications you've produced!

**Comment by pappasam** [comment]
@dimbleby looks like pygls was just released, let me know when you believe this is mergeable and I'll so some deeper tests then.

**Comment by dimbleby** [comment]
I re-pushed to use pygls 0.10.0, should be good for a closer look now.

**Comment by dimbleby** [comment]
actually I've made a tiny mess of rewriting the history and my inner perfectionist isn't quite happy, will fix shortly.

**Comment by dimbleby** [comment]
I've just noticed pygls_type_overrides.py.

That looks as though it might be workaround for things that no longer need workaround, though I'm not sure exactly what.  Can we remove that too, do you think?

**Comment by dimbleby** [comment]
Yes, looks like this went in for #38 and was a particular case of the thing where pygls liked to send `null`. But it doesn't do that now, so will remove this too.

**Comment by dimbleby** [comment]
Oh, and also the private reimplementation of `RenameFile`, surely can remove that too.

**Comment by pappasam** [comment]
This PR relates to https://github.com/openlawlibrary/pygls/issues/151

**Review by pappasam — APPROVED** [review]
lgtm!

**Pull request merged**
