### PR TITLE
WIP: Semantic tokens support

### PR DESCRIPTION
**Pull request by tonich-sh**
Currently is very slow.

### CODE REVIEW

**Comment by pappasam** [comment]
@tonich-sh to run the tests locally: `make test`

**Comment by tonich-sh** [comment]
> @tonich-sh to run the tests locally: `make test`

Ok, thanks.

**Comment by pappasam** [comment]
Sorry for the late response (been distracted recently), I'll respond more quickly from here on out. I'm guessing we haven't-yet implemented a mechanism to expose these capabilities to language clients? When I run `:call CocActionAsync('showSemanticHighlightInfo')` in coc, it returns the following message:

```
Semantic highlights info

SemanticTokens provider not found, your languageserver may
not support it
```

I assume that, given the WIP label, you're still working on exposing that final piece?

**Comment by tonich-sh** [comment]
> 

I didn't tested this feature with coc, only with VSCode. In VSCode semantic tokens works.
There is another problem: vscode-python calls SemanticTokens/full before SemanticTokens/range. And I'm trying to make SemanticTokens/full asynchronous.

**Comment by pappasam** [comment]
Closing this for now due to inactivity, feel free to re-open if any more progress is made!

**Pull request closed without merging**
