### PR TITLE
Sort completions by public, private, and dunder

### PR DESCRIPTION
**Pull request by pappasam**
Resolves https://github.com/pappasam/jedi-language-server/issues/184

### CODE REVIEW

**Comment by pappasam** [comment]
@karthiknadig please test this out and let me know if it resolves your issue. Here's what I get now:

image

**Comment by karthiknadig** [comment]
Looks better, but I think the content should also be sorted:
image

**Comment by pappasam** [comment]
@karthiknadig good catch, please test out the latest commit and let me know if that satisfies!

**Comment by karthiknadig** [comment]
That works!!!

**Pull request merged**
