### PR TITLE
Fix compatibility issue with lsprotocol by pinning version in pyproject.toml

### PR DESCRIPTION
**Pull request by arthur-k-kochi**
As discussed in issue #302, the latest version of `lsprotocol` (`2024.0.0a1`) has deprecated the `TraceValues` from `lsprotocol.types`, which caused failures when initiating the `jedi-language-server`. This issue led to an inability to start the server as detailed in the error logs.

To resolve this, I have proposed a change in the `pyproject.toml` to pin the `lsprotocol` version to `<=2023.0.1`. Additionally, I have updated the `poetry.lock` file to reflect this change.

Please note that this is my first pull request outside of my personal projects. I welcome any feedback or corrections if there are better ways to handle this issue. Thank you for considering this contribution!

### CODE REVIEW

**Comment by arthur-k-kochi** [comment]
Fix: #302

**Comment by arthur-k-kochi** [comment]
I only changed the version specification of `lsprotocol`, but the automatic changes in `poetry.lock` may have caused some malfunctions in the package. Are there any ways to check if the updated package runs correctly?

**Comment by pappasam** [comment]
Yep, check out the README's section on local development / how to run the tests locally: https://github.com/pappasam/jedi-language-server?tab=readme-ov-file#local-development.

Regarding the update: I think the issue might be that, by relying on `>=2022.0.0a9` in `pyproject.toml`, poetry might be implicitly allowing pre-prereleases. Since `lsprotocol` now has non-pre-releases, we should probably update `pyproject.toml` to not allow pre-releases (maybe by just specifying `>=2023.0.1`).

I'd update your PR to include that line, run poetry, and see if things work. The issue here is that the type system isn't resolving correctly, since `pygls` doesn't think we're allowing pre-releases.

**Comment by pappasam** [comment]
Resolved by: https://github.com/pappasam/jedi-language-server/pull/312

**Pull request closed without merging**
